// 天体 × サイン 解釈テキスト（ワンライン）
export const PLANET_SIGN_INTERP: Record<string, Record<string, string>> = {
  Sun: {
    Aries:       '強い自己主張で先頭に立つ先駆者',
    Taurus:      '安定と実利を重んじる粘り強い意志',
    Gemini:      '好奇心旺盛で多才な表現者',
    Cancer:      '感情豊かで家族を守る母性的自己',
    Leo:         '華やかな存在感と創造的な自尊心',
    Virgo:       '分析的で完璧を求める奉仕精神',
    Libra:       '調和と公平を求める社交的な人格',
    Scorpio:     '深い洞察力と変革を恐れない強さ',
    Sagittarius: '自由と真理を追う楽天的な探求者',
    Capricorn:   '目標に向かって登り詰める野心家',
    Aquarius:    '独創的で社会変革を夢見る革新者',
    Pisces:      '豊かな感受性と境界を超える共感力',
  },
  Moon: {
    Aries:       '感情が爆発的で直感に従って動く',
    Taurus:      '安定した感情、心の安らぎを重視',
    Gemini:      '気分が変わりやすく知的好奇心旺盛',
    Cancer:      '深い共感力で感情と記憶に敏感',
    Leo:         '情熱的でドラマチックな感情表現',
    Virgo:       '感情を内に抑えがち、細部に敏感',
    Libra:       '感情的な調和を好み決断に迷いがち',
    Scorpio:     '感情が深く強烈、嫉妬心も強い',
    Sagittarius: '楽観的で自由を求める感情の持ち主',
    Capricorn:   '感情を制御し責任感から行動する',
    Aquarius:    '感情より理性を優先する冷静さ',
    Pisces:      '感情の海に溶け込む夢想的な感性',
  },
  Mercury: {
    Aries:       '直接的・即断的な思考と言動',
    Taurus:      'じっくり考え実用を重視した言葉',
    Gemini:      '機転が利く多方面への興味と知識',
    Cancer:      '直感的・感情的な思考パターン',
    Leo:         '自信ある表現とドラマチックな語り口',
    Virgo:       '精緻な分析力と鋭い批評眼の持ち主',
    Libra:       '公平な判断力と外交的な言葉選び',
    Scorpio:     '洞察力鋭く秘密や本質を嗅ぎ取る',
    Sagittarius: '大局的視点と哲学的な語り口',
    Capricorn:   '実用的・現実的で言葉に重みがある',
    Aquarius:    '独創的・理論的な未来志向の発想',
    Pisces:      '直感とイメージで考える詩的表現',
  },
  Venus: {
    Aries:       '情熱的・積極的に愛を表現する',
    Taurus:      '安定と官能を求める深い愛情',
    Gemini:      '軽快で知的、多様な関係を楽しむ',
    Cancer:      '母性的で献身的な愛、家庭を大切に',
    Leo:         '華やかなロマンスを求め与える愛',
    Virgo:       '奉仕と細やかな気遣いで愛を示す',
    Libra:       '調和と美を愛し理想のパートナーを求める',
    Scorpio:     '深く独占的な愛、全か無かの感情',
    Sagittarius: '自由を尊重し冒険的なロマンスを好む',
    Capricorn:   '堅実で長期的な愛、結果を出す恋愛',
    Aquarius:    '友愛的・独立心旺盛で型破りな関係',
    Pisces:      '無条件の愛で溶け合うような深い絆',
  },
  Mars: {
    Aries:       '圧倒的な行動力と強烈な競争心',
    Taurus:      '粘り強く執念深く目標を追い続ける',
    Gemini:      '多方向に散る情熱、議論が得意',
    Cancer:      '感情に動かされる守護本能の行動力',
    Leo:         '劇的で誇り高いエネルギーの持ち主',
    Virgo:       '緻密な計画で着実に実行する力',
    Libra:       '協力しながら目標を達成するスタイル',
    Scorpio:     '深い執着と強烈な集中力で突き進む',
    Sagittarius: '理想と自由のための大胆な行動',
    Capricorn:   '地道に登り詰める持続的な野心',
    Aquarius:    '革新と変革のための反骨精神',
    Pisces:      '直感とインスピレーションで動く',
  },
  Jupiter: {
    Aries:       '挑戦と開拓で幸運を引き寄せる',
    Taurus:      '地道な努力が物質的豊かさを生む',
    Gemini:      '知識と情報の集積が運を開く',
    Cancer:      '家庭・感情の豊かさから拡大する',
    Leo:         '創造と表現で大きく花開く才能',
    Virgo:       '細部への誠実さが信頼と運を生む',
    Libra:       '人脈とバランスで運が広がる',
    Scorpio:     '変革と深掘りで大きな成長を遂げる',
    Sagittarius: '冒険と哲学が人生を豊かにする',
    Capricorn:   '長期的戦略と忍耐が大きな成果に',
    Aquarius:    '独自の視点と社会貢献で拡大する',
    Pisces:      '霊性と共感力が幸運の泉となる',
  },
  Saturn: {
    Aries:       '独立心と自己主張を鍛えられる課題',
    Taurus:      '物質的安定のための努力と忍耐',
    Gemini:      '思考と言語を深化させる訓練',
    Cancer:      '感情の安定と家族関係が人生の課題',
    Leo:         '自己表現と承認欲求に向き合う試練',
    Virgo:       '完璧主義を克服し実践スキルを磨く',
    Libra:       '対人関係と公平性を厳しく問われる',
    Scorpio:     '権力・欲求・変革への深い試練',
    Sagittarius: '信念と自由の責任を問われる人生',
    Capricorn:   '社会的責任と野心を全うする集大成',
    Aquarius:    '革新と秩序のバランスを学ぶ',
    Pisces:      '幻想と現実の境界線を引く訓練',
  },
  Uranus: {
    Aries:       '突発的な自己革命と独立への衝動',
    Taurus:      '価値観・経済への革新的な変化',
    Gemini:      '情報・通信技術の急速な変革',
    Cancer:      '家族・感情パターンからの解放',
    Leo:         '表現・創造における独自性の爆発',
    Virgo:       '健康・労働分野の革新的改善',
    Libra:       '対人関係・社会規範の再定義',
    Scorpio:     '深層心理・権力構造の変革',
    Sagittarius: '宗教・哲学・教育の解放',
    Capricorn:   '社会システム・制度の革命',
    Aquarius:    '人道主義・テクノロジーの刷新',
    Pisces:      '精神性・芸術・信仰の解放',
  },
  Neptune: {
    Aries:       '個の理想と自己犠牲の融合',
    Taurus:      '物質への幻想と美的感性の高まり',
    Gemini:      '情報と幻想が混ざり合う感性',
    Cancer:      '家族・故郷への深い夢と郷愁',
    Leo:         '芸術・エンタメへの強い理想主義',
    Virgo:       '奉仕と健康への理想と幻想',
    Libra:       '愛と平和への深い理想主義',
    Scorpio:     '神秘・変容への強烈な感受性',
    Sagittarius: '信仰・探求への精神的高揚',
    Capricorn:   '現実の中に霊性を見出す感性',
    Aquarius:    '人類愛と宇宙的ビジョンの持ち主',
    Pisces:      '無境界の深い神秘的共感力',
  },
  Pluto: {
    Aries:       '自己と社会の根本的な変革者',
    Taurus:      '価値・所有・資源の権力的変容',
    Gemini:      '言語・情報・知の深部変革',
    Cancer:      '家族・感情の深部からの再生',
    Leo:         '権力・自己表現の根本的変容',
    Virgo:       '仕事・健康・奉仕の徹底的刷新',
    Libra:       '対人・社会正義の根本変革',
    Scorpio:     '生死・変容・権力の極限を生きる',
    Sagittarius: '信仰・哲学・真実の徹底的変革',
    Capricorn:   '社会システム・権威の破壊と再生',
    Aquarius:    '人類の在り方を根本から変革',
    Pisces:      '霊性・無意識・集合意識の大変容',
  },
  NNode: {
    Aries:       '自立と行動力を磨く魂の方向性',
    Taurus:      '安定・物質的充足に向かう魂の課題',
    Gemini:      '知識・コミュニケーションを深める使命',
    Cancer:      '感情的な繋がりと家庭を育む使命',
    Leo:         '創造と自己表現で輝く魂の方向性',
    Virgo:       '奉仕と完璧さを追求する魂の課題',
    Libra:       'パートナーシップと調和を育む使命',
    Scorpio:     '深い変容と再生を生きる魂の課題',
    Sagittarius: '探求・哲学・自由を追求する使命',
    Capricorn:   '社会的責任と達成に向かう使命',
    Aquarius:    '人類への貢献と革新を生きる使命',
    Pisces:      '霊性・共感・無条件の愛を育む使命',
  },
}

// ASC・MC 用（サインのみで解釈）
export const SIGN_THEME: Record<string, string> = {
  Aries:       '活発・自己主張が強い第一印象',
  Taurus:      '穏やかで信頼感のある外見と態度',
  Gemini:      '知的で軽快、好奇心旺盛な印象',
  Cancer:      '温かく守護的で感情豊かな印象',
  Leo:         '華やかで自信に満ちた存在感',
  Virgo:       '清潔感があり分析的・謙虚な印象',
  Libra:       '美しくバランスの取れた社交的印象',
  Scorpio:     '神秘的で強烈、磁力のある印象',
  Sagittarius: '開放的で楽観的、自由を愛する印象',
  Capricorn:   '真面目で落ち着き、信頼感のある印象',
  Aquarius:    '独自性と知性を放つ個性的な印象',
  Pisces:      '柔らかく夢見がちな神秘的な印象',
}

// ハウステーマ
export const HOUSE_THEMES: Record<number, string> = {
  1:  '自己・外見',
  2:  '財産・価値観',
  3:  '知性・兄弟',
  4:  '家庭・ルーツ',
  5:  '創造・恋愛',
  6:  '仕事・健康',
  7:  '対人・結婚',
  8:  '変容・遺産',
  9:  '哲学・海外',
  10: '地位・仕事',
  11: '友人・理想',
  12: '無意識・霊性',
}

// アスペクト解説
export const ASPECT_INTERP: Record<string, { jp: string; symbol: string; desc: string }> = {
  Conjunction:    { jp: 'コンジャンクション', symbol: '☌', desc: '2天体が融合・強化。エネルギーが一点に集中し、その天体の特質が極端に強まる。吉凶は関係する天体の性質による。' },
  Sextile:        { jp: 'セクスタイル',       symbol: '⚹', desc: '才能や機会がスムーズに流れる調和の角度。努力を後押しするやわらかいサポート。' },
  Square:         { jp: 'スクエア',           symbol: '□', desc: '緊張と摩擦を生む挑戦的な角度。困難を乗り越えることで大きな成長を促す原動力になる。' },
  Trine:          { jp: 'トライン',           symbol: '△', desc: '最も恵まれた調和の角度。才能が自然に発揮され、関係する分野で物事がスムーズに進む。' },
  Opposition:     { jp: 'オポジション',       symbol: '☍', desc: '対立と統合のダイナミクス。外部との衝突や他者との関わりを通じてバランスを学ぶ。' },
  Quincunx:       { jp: 'クインカンクス',     symbol: '⚻', desc: '調整が必要な微妙な不一致。継続的な修正と適応を求められるが、独特の創造性も生まれる。' },
  Sesquiquadrate: { jp: 'セスキコードレイト', symbol: '∠', desc: 'スクエアより微細な摩擦。内的なフラストレーションや焦りを示し、見直しを促す角度。' },
}

export function getPlanetSignInterp(planetName: string, sign: string): string | null {
  const interp = PLANET_SIGN_INTERP[planetName]?.[sign]
  if (interp) return interp
  // ASC / MC はサインテーマで代用
  if (planetName === 'ASC' || planetName === 'MC') return SIGN_THEME[sign] ?? null
  return null
}
